// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAY6balP9HgNim57VXXWUm7UsNgpPuxpQw',
    appId: '1:786532202795:web:779b0fe607eeb62a64ad6e',
    messagingSenderId: '786532202795',
    projectId: 'test-93931',
    authDomain: 'test-93931.firebaseapp.com',
    storageBucket: 'test-93931.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5rORRSh-_IeyCxTH9KhX9ixhcuvgT4E0',
    appId: '1:786532202795:android:920e8d7a87d524f964ad6e',
    messagingSenderId: '786532202795',
    projectId: 'test-93931',
    storageBucket: 'test-93931.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHvqaszvZAzRicfCXCZPKV9awvUCemxbA',
    appId: '1:786532202795:ios:a436adcf7c27db2e64ad6e',
    messagingSenderId: '786532202795',
    projectId: 'test-93931',
    storageBucket: 'test-93931.firebasestorage.app',
    iosBundleId: 'com.example.firestoreTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHvqaszvZAzRicfCXCZPKV9awvUCemxbA',
    appId: '1:786532202795:ios:a436adcf7c27db2e64ad6e',
    messagingSenderId: '786532202795',
    projectId: 'test-93931',
    storageBucket: 'test-93931.firebasestorage.app',
    iosBundleId: 'com.example.firestoreTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAY6balP9HgNim57VXXWUm7UsNgpPuxpQw',
    appId: '1:786532202795:web:620e3fda257ec9c364ad6e',
    messagingSenderId: '786532202795',
    projectId: 'test-93931',
    authDomain: 'test-93931.firebaseapp.com',
    storageBucket: 'test-93931.firebasestorage.app',
  );
}
